### ISSUE TITLE
Option for ad label

### ISSUE THREAD

**Issue by yogeshbeniwal** [Automattic/newspack-ads#193]
Ad Label clearly differentiate ads from main content. Recommended to provide an option to customise ad label for all ad placements.

**Comment by kmwilkerson** [comment]
Add a text field to add label to ads. Example using "Advertisement":

![Screen Shot 2022-01-07 at 12 43 34 PM](https://user-images.githubusercontent.com/20666833/148591781-3cb8b9a0-c1e8-4e17-8752-ccd1e98905ce.png)

@miguelpeixe I do like [your idea ](https://github.com/Automattic/newspack-ads/pull/228#issuecomment-976733818)of making this a placement setting rather than a global setting since a label on certain positions would look odd (thinking of above/below header and sticky footer). This would mostly be used for in-content placements and blocks on the homepage.

**Comment by yogeshbeniwal** [comment]
@miguelpeixe Thanks for quick PR. Should this Ad label works for In content after paragraph blocks also? No Label is shown while using legacy widgets for ad placement. Ok for sidebar and headers ads.

**Comment by miguelpeixe** [comment]
The Ad labels should only work for ads placed through the global placements wizard. The disabling of legacy mode should allow for the label to be displayed in SCAIP ads.

**Comment by yogeshbeniwal** [comment]
@miguelpeixe Thanks, it does. IMO from Ux/UI point of view can remove Label from Mobile Sticky Footer Ad unit
