### ISSUE TITLE
Layout shift with ads

### ISSUE THREAD

**Issue by yogeshbeniwal** [Automattic/newspack-ads#200]
Ads with multi size options are causing layout shifts. Specially above/below header and sidebar ad in viewport will lead to negative effect on google ranking.

Recommended solution:
Reserve space for the largest size configured to serve.

**Comment by kmwilkerson** [comment]
@yogeshbeniwal When a site is fully AMP, a max height is set by default. However for sites that choose not to use AMP, we do not want to set such design restrictions. Because optimizing CLS from ads is a recommendation and not a requirement, we believe it's important to leave the decision in the hands of publishers.
