### ISSUE TITLE
Full width ad for one column template

### ISSUE THREAD

**Issue by yogeshbeniwal** [Automattic/newspack-ads#295]
Full width ad for one column template will be a good option to have for ad blocks inserted within content. Not sure if this has to be taken here or SCAIP or Newspack theme repo.

**Comment by kmwilkerson** [comment]
@yogeshbeniwal In the PR linked above, you'll be able to set a full-width background color to in-content ads within single column posts. Additionally, we'll also be adding a key-value pair to allow for "post template" targeting from GAM so that you can serve wider creative to single column posts specifically. Within the Newspack ads wizard, you can edit the ad units used for in-content placements to accept these wider standard sizes, or even custom sizes. Having the post template targeting option will allow you to use the same in-content ad units on all posts regardless of template, but only serve creative wider than 728px to single columns posts.

**Comment by earcos** [comment]
Just wanted to bring attention to the fact that full width ads for one column template do not work on AMP :(

**Comment by miguelpeixe** [comment]
@earcos can you provide a screenshot or describe how it's behaving?

**Comment by earcos** [comment]
Sure. This is an example. This position is configured for 970x250 or 970x90 or 728x90. AMP version ONLY shows 728x90, regular version shows the 970x90 or 970x250 every time. HTML shows the 970x250 code, but with the hidden attribute.

https://hipertextual.com/2022/02/lobezno-wolverine-doctor-strange-2-giro-inesperado

<img width="1344" alt="CleanShot 2022-02-24 at 16 54 06@2x" src="https://user-images.githubusercontent.com/16387856/155559909-38642752-d511-4497-8a61-48934da593ae.png">
