### ISSUE TITLE
Skip Paragraph from block count when below minimum content length 

### ISSUE THREAD

**Issue by yogeshbeniwal** [Automattic/newspack-ads#311]
While using short paragraphs for content, it create a perception of ads appearance too frequent (Same block settings is ok for large paragraphs). An option to exclude paragraph from count when below minimum content length will resolve this e.g. Exclude when below XX words.

**Comment by kmwilkerson** [comment]
@yogeshbeniwal Because the ability to edit ad placement already exists by counting blocks, we don't believe word count is necessary at this time. If short paragraphs are common, we would recommend the publisher increase the block count for when to show ads. 

![Screen Shot 2022-02-23 at 2 49 53 PM](https://user-images.githubusercontent.com/20666833/155405998-0c8873aa-0cf0-4874-96d1-7d8a75c84525.png)

**Comment by yogeshbeniwal** [comment]
@kmwilkerson Thank you for your response, this was raised for scenario where few of the article content like news have short paragraph than evergreen content. Having same settings across doesn't give optimized results.

Was hoping if at least we can keep it parked under some milestone, even if there is no timeline for it yet.
