### ISSUE TITLE
Pre-defined ad placements: make them filterable

### ISSUE THREAD

**Issue by dero** [Automattic/newspack-ads#407]
**Is your feature request related to a problem? Please describe.**
The advertising wizard [defines a set of pre-defined ad placements](https://github.com/Automattic/newspack-plugin/blob/45be0ad10c58c8572685bf5e81e7332c113ae392/includes/wizards/class-advertising-wizard.php#L60) and a [method](https://github.com/Automattic/newspack-plugin/blob/45be0ad10c58c8572685bf5e81e7332c113ae392/includes/wizards/class-advertising-wizard.php#L459) to retrieve the array.

While the pre-defined set is well chosen and maps well to placements chosen by many publishers, most publishers could use a few custom placements that would cater to their individual needs. It would help if one could hook (`add_filter`) into placements data and be able to define these custom placements.

**Describe the solution you'd like**
Add filters (`apply_filter`) to the codebase so that placement data can be manipulated from other plugins and themes.

**Describe alternatives you've considered**
One way to achieve a similar effect currently is to register custom sidebars and use the provided Ad widget to assign ads to predefined placements this way. Being able to tap into the main ad association screen in Newspack would be much more seamless and intuitive, though.

**Additional context**
No additional context.

**Comment by adekbadek** [comment]
[Updated code location](https://github.com/Automattic/newspack-ads/blob/ef1441952228f763e9efe40839db62cda2514755/includes/class-placements.php#L383)

**Comment by miguelpeixe** [comment]
Ads placements have changed a lot since the writing of this issue. You can register new placements by using the [`Newspack_Ads::register_placement()`](https://github.com/Automattic/newspack-ads/blob/c2aaf62eace044a839b8cd52b0db163b181eb554/includes/class-placements.php#L415-L423) method.

Example of a custom placement:

```php
function my_register_placement() {
	if( ! method_exists( '\Newspack_Ads', 'register_placement' ) ) {
		return false;
	}
	$placement_key    = 'my_custom_placement';
	$placement_config = array(
		'name'        => __( 'My Custom Placement', 'my-textdomain' ),
		'description' => __( 'Choose an ad unit to display in this custom placement', 'my-textdomain' ),
		'hook_name'   => 'my_custom_placement',
	);
	\Newspack_Ads::register_placement( $placement_id, $placement_config );
}
add_action( 'init', 'my_register_placement' );
```

To determine where the ad should be rendered, add the action hook on your theme where you'd like it to be displayed:

```php
<?php do_action( 'my_custom_placement' ); ?>
``` 

You can see a full list of available config options:

https://github.com/Automattic/newspack-ads/blob/c2aaf62eace044a839b8cd52b0db163b181eb554/includes/class-placements.php#L331-L348

**Comment by dero** [comment]
Looks great, thank you for the overview, @miguelpeixe – from my PoV this can be closed.

**Comment by miguelpeixe** [comment]
Thank you @dero!
