### ISSUE TITLE
Provide default GAM ad units

### ISSUE THREAD

**Issue by miguelpeixe** [Automattic/newspack-ads#410]
To be stored locally and built specifically to fit best in how the global placements connect with the Newspack theme.

These units should be always available but not immediately synced to the publisher’s GAM inventory. It should work out-of-the-box for publishers using the GAM connection or not (open-source publishers).

Once a publisher edits a default unit, it becomes part of its GAM inventory and local database.

The proposed defaults are:

Unit name | Unit sizes
-- | --
Newspack Global Below Header | 320x50 320x100 728x90 970x90 970x250
Newspack Sticky Footer | 320x50 320x100
Newspack Sidebar 1 | 300x250 300x600
Newspack Sidebar 2 | 300x250 300x600 (stick to top)
Newspack In-Article 1 | 728x90 300x250
Newspack In-Article 2 | 728x90 300x250
Newspack In-Article 3 | 728x90 300x250

**Comment by yogeshbeniwal** [comment]
Thank you for detailed response. I had drawn same conclusion for footer ad, but after lazy load feature, have started implementing on each website to extract maximum out of ads without hitting viewability.

> Likely due to advertisers being able to better convey a message, as 300 pixels can be limiting. We have not found that 20 pixels makes much of a difference for the user experience.

From Ux point of view my concern is for height 100 px vs 50 px rather than width of 300 vs 320.
